name: Build

on: [push]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [crawler, line, slack, twitter]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build ${{ matrix.dir }}
      run: docker build containers/${{ matrix.dir }} --file containers/${{ matrix.dir }}/Dockerfile
